### ISSUE TITLE
How to use this library?

### ISSUE THREAD

**Issue by heitorPB** [Flickr-Foundation/flickr-photos-api#106]
How do I start using this library? The provided example in the README does not work with the latest version (2.11.2):

```python
In [1]: from flickr_photos_api import FlickrApi

In [2]: api = FlickrApi(api_key="…", user_agent="…")
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[2], line 1
----> 1 api = FlickrApi(api_key="…", user_agent="…")

TypeError: HttpxImplementation.__init__() got an unexpected keyword argument 'api_key'

In [3]: api = FlickrApi()
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[3], line 1
----> 1 api = FlickrApi()

TypeError: HttpxImplementation.__init__() missing 1 required keyword-only argument: 'client'
```

**Comment by alexwlchan** [comment]
Ah, sorry, the README is a bit out of date! The current approach is `FlickrApi.with_api_key` – I've updated the instructions.
